"""init migration

Revision ID: aeef94dc0aeb
Revises: 
Create Date: 2025-11-06 23:49:00.651617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeef94dc0aeb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False, comment='Book ID'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Book title'),
    sa.Column('author', sa.String(length=500), nullable=False, comment='Book author'),
    sa.Column('isbn', sa.String(length=20), nullable=False, comment='Book ISBN'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Book category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
